{
  "swagger": "2.0",
  "info": {
    "version": "v3",
    "title": "YouTube Data API v3",
    "description": "The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    }
  },
  "host": "youtube.googleapis.com",
  "basePath": "/",
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/youtube": "Manage your YouTube account",
        "https://www.googleapis.com/auth/youtube.channel-memberships.creator": "See a list of your current active channel members, their current level, and when they became a member",
        "https://www.googleapis.com/auth/youtube.force-ssl": "See, edit, and permanently delete your YouTube videos, ratings, comments and captions",
        "https://www.googleapis.com/auth/youtube.readonly": "View your YouTube account",
        "https://www.googleapis.com/auth/youtube.upload": "Manage your YouTube videos",
        "https://www.googleapis.com/auth/youtubepartner": "View and manage your assets and associated content on YouTube",
        "https://www.googleapis.com/auth/youtubepartner-channel-audit": "View private information of your YouTube channel relevant during the audit process with a YouTube partner"
      }
    },
    "Oauth2c": {
      "type": "oauth2",
      "description": "Oauth 2.0 authorizationCode authentication",
      "flow": "accessCode",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "scopes": {
        "https://www.googleapis.com/auth/youtube": "Manage your YouTube account",
        "https://www.googleapis.com/auth/youtube.channel-memberships.creator": "See a list of your current active channel members, their current level, and when they became a member",
        "https://www.googleapis.com/auth/youtube.force-ssl": "See, edit, and permanently delete your YouTube videos, ratings, comments and captions",
        "https://www.googleapis.com/auth/youtube.readonly": "View your YouTube account",
        "https://www.googleapis.com/auth/youtube.upload": "Manage your YouTube videos",
        "https://www.googleapis.com/auth/youtubepartner": "View and manage your assets and associated content on YouTube",
        "https://www.googleapis.com/auth/youtubepartner-channel-audit": "View private information of your YouTube channel relevant during the audit process with a YouTube partner"
      }
    }
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/youtube/v3/abuseReports": {
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.abuseReports.insert",
        "tags": [
          "abuseReports"
        ],
        "operationId": "youtube.abuseReports.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/activities": {
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.activities.list",
        "tags": [
          "activities"
        ],
        "operationId": "youtube.activities.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          }
        ]
      }
    },
    "/youtube/v3/captions": {
      "delete": {
        "description": "Deletes a resource.",
        "summary": "youtube.captions.delete",
        "tags": [
          "captions"
        ],
        "operationId": "youtube.captions.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.captions.list",
        "tags": [
          "captions"
        ],
        "operationId": "youtube.captions.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.captions.insert",
        "tags": [
          "captions"
        ],
        "operationId": "youtube.captions.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing resource.",
        "summary": "youtube.captions.update",
        "tags": [
          "captions"
        ],
        "operationId": "youtube.captions.update",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/captions/{id}": {
      "get": {
        "description": "Downloads a caption track.",
        "summary": "youtube.captions.download",
        "tags": [
          "captions"
        ],
        "operationId": "youtube.captions.download",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/channelBanners/insert": {
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.channelBanners.insert",
        "tags": [
          "channelBanners"
        ],
        "operationId": "youtube.channelBanners.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.upload"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.upload"
            ]
          }
        ]
      }
    },
    "/youtube/v3/channels": {
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.channels.list",
        "tags": [
          "channels"
        ],
        "operationId": "youtube.channels.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner-channel-audit"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner-channel-audit"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing resource.",
        "summary": "youtube.channels.update",
        "tags": [
          "channels"
        ],
        "operationId": "youtube.channels.update",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/channelSections": {
      "delete": {
        "description": "Deletes a resource.",
        "summary": "youtube.channelSections.delete",
        "tags": [
          "channelSections"
        ],
        "operationId": "youtube.channelSections.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.channelSections.list",
        "tags": [
          "channelSections"
        ],
        "operationId": "youtube.channelSections.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.channelSections.insert",
        "tags": [
          "channelSections"
        ],
        "operationId": "youtube.channelSections.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing resource.",
        "summary": "youtube.channelSections.update",
        "tags": [
          "channelSections"
        ],
        "operationId": "youtube.channelSections.update",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/comments": {
      "delete": {
        "description": "Deletes a resource.",
        "summary": "youtube.comments.delete",
        "tags": [
          "comments"
        ],
        "operationId": "youtube.comments.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.comments.list",
        "tags": [
          "comments"
        ],
        "operationId": "youtube.comments.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.comments.insert",
        "tags": [
          "comments"
        ],
        "operationId": "youtube.comments.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing resource.",
        "summary": "youtube.comments.update",
        "tags": [
          "comments"
        ],
        "operationId": "youtube.comments.update",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/comments/markAsSpam": {
      "post": {
        "description": "Expresses the caller's opinion that one or more comments should be flagged as spam.",
        "summary": "youtube.comments.markAsSpam",
        "tags": [
          "comments"
        ],
        "operationId": "youtube.comments.markAsSpam",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/comments/setModerationStatus": {
      "post": {
        "description": "Sets the moderation status of one or more comments.",
        "summary": "youtube.comments.setModerationStatus",
        "tags": [
          "comments"
        ],
        "operationId": "youtube.comments.setModerationStatus",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/commentThreads": {
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.commentThreads.list",
        "tags": [
          "commentThreads"
        ],
        "operationId": "youtube.commentThreads.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.commentThreads.insert",
        "tags": [
          "commentThreads"
        ],
        "operationId": "youtube.commentThreads.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing resource.",
        "summary": "youtube.youtube.v3.updateCommentThreads",
        "tags": [
          "youtube"
        ],
        "operationId": "youtube.youtube.v3.updateCommentThreads",
        "deprecated": false
      }
    },
    "/youtube/v3/i18nLanguages": {
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.i18nLanguages.list",
        "tags": [
          "i18nLanguages"
        ],
        "operationId": "youtube.i18nLanguages.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/i18nRegions": {
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.i18nRegions.list",
        "tags": [
          "i18nRegions"
        ],
        "operationId": "youtube.i18nRegions.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/liveBroadcasts": {
      "delete": {
        "description": "Delete a given broadcast.",
        "summary": "youtube.liveBroadcasts.delete",
        "tags": [
          "liveBroadcasts"
        ],
        "operationId": "youtube.liveBroadcasts.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieve the list of broadcasts associated with the given channel.",
        "summary": "youtube.liveBroadcasts.list",
        "tags": [
          "liveBroadcasts"
        ],
        "operationId": "youtube.liveBroadcasts.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new stream for the authenticated user.",
        "summary": "youtube.liveBroadcasts.insert",
        "tags": [
          "liveBroadcasts"
        ],
        "operationId": "youtube.liveBroadcasts.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing broadcast for the authenticated user.",
        "summary": "youtube.liveBroadcasts.update",
        "tags": [
          "liveBroadcasts"
        ],
        "operationId": "youtube.liveBroadcasts.update",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/liveBroadcasts/bind": {
      "post": {
        "description": "Bind a broadcast to a stream.",
        "summary": "youtube.liveBroadcasts.bind",
        "tags": [
          "liveBroadcasts"
        ],
        "operationId": "youtube.liveBroadcasts.bind",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/liveBroadcasts/cuepoint": {
      "post": {
        "description": "Insert cuepoints in a broadcast",
        "summary": "youtube.liveBroadcasts.insertCuepoint",
        "tags": [
          "liveBroadcasts"
        ],
        "operationId": "youtube.liveBroadcasts.insertCuepoint",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/liveBroadcasts/transition": {
      "post": {
        "description": "Transition a broadcast to a given status.",
        "summary": "youtube.liveBroadcasts.transition",
        "tags": [
          "liveBroadcasts"
        ],
        "operationId": "youtube.liveBroadcasts.transition",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/liveChat/bans": {
      "delete": {
        "description": "Deletes a chat ban.",
        "summary": "youtube.liveChatBans.delete",
        "tags": [
          "liveChatBans"
        ],
        "operationId": "youtube.liveChatBans.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.liveChatBans.insert",
        "tags": [
          "liveChatBans"
        ],
        "operationId": "youtube.liveChatBans.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/liveChat/messages": {
      "delete": {
        "description": "Deletes a chat message.",
        "summary": "youtube.liveChatMessages.delete",
        "tags": [
          "liveChatMessages"
        ],
        "operationId": "youtube.liveChatMessages.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.liveChatMessages.list",
        "tags": [
          "liveChatMessages"
        ],
        "operationId": "youtube.liveChatMessages.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.liveChatMessages.insert",
        "tags": [
          "liveChatMessages"
        ],
        "operationId": "youtube.liveChatMessages.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/liveChat/moderators": {
      "delete": {
        "description": "Deletes a chat moderator.",
        "summary": "youtube.liveChatModerators.delete",
        "tags": [
          "liveChatModerators"
        ],
        "operationId": "youtube.liveChatModerators.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.liveChatModerators.list",
        "tags": [
          "liveChatModerators"
        ],
        "operationId": "youtube.liveChatModerators.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.liveChatModerators.insert",
        "tags": [
          "liveChatModerators"
        ],
        "operationId": "youtube.liveChatModerators.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/liveStreams": {
      "delete": {
        "description": "Deletes an existing stream for the authenticated user.",
        "summary": "youtube.liveStreams.delete",
        "tags": [
          "liveStreams"
        ],
        "operationId": "youtube.liveStreams.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieve the list of streams associated with the given channel. --",
        "summary": "youtube.liveStreams.list",
        "tags": [
          "liveStreams"
        ],
        "operationId": "youtube.liveStreams.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new stream for the authenticated user.",
        "summary": "youtube.liveStreams.insert",
        "tags": [
          "liveStreams"
        ],
        "operationId": "youtube.liveStreams.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing stream for the authenticated user.",
        "summary": "youtube.liveStreams.update",
        "tags": [
          "liveStreams"
        ],
        "operationId": "youtube.liveStreams.update",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ]
      }
    },
    "/youtube/v3/members": {
      "get": {
        "description": "Retrieves a list of members that match the request criteria for a channel.",
        "summary": "youtube.members.list",
        "tags": [
          "members"
        ],
        "operationId": "youtube.members.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.channel-memberships.creator"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.channel-memberships.creator"
            ]
          }
        ]
      }
    },
    "/youtube/v3/membershipsLevels": {
      "get": {
        "description": "Retrieves a list of all pricing levels offered by a creator to the fans.",
        "summary": "youtube.membershipsLevels.list",
        "tags": [
          "membershipsLevels"
        ],
        "operationId": "youtube.membershipsLevels.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.channel-memberships.creator"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.channel-memberships.creator"
            ]
          }
        ]
      }
    },
    "/youtube/v3/playlistItems": {
      "delete": {
        "description": "Deletes a resource.",
        "summary": "youtube.playlistItems.delete",
        "tags": [
          "playlistItems"
        ],
        "operationId": "youtube.playlistItems.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.playlistItems.list",
        "tags": [
          "playlistItems"
        ],
        "operationId": "youtube.playlistItems.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.playlistItems.insert",
        "tags": [
          "playlistItems"
        ],
        "operationId": "youtube.playlistItems.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing resource.",
        "summary": "youtube.playlistItems.update",
        "tags": [
          "playlistItems"
        ],
        "operationId": "youtube.playlistItems.update",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/playlists": {
      "delete": {
        "description": "Deletes a resource.",
        "summary": "youtube.playlists.delete",
        "tags": [
          "playlists"
        ],
        "operationId": "youtube.playlists.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.playlists.list",
        "tags": [
          "playlists"
        ],
        "operationId": "youtube.playlists.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.playlists.insert",
        "tags": [
          "playlists"
        ],
        "operationId": "youtube.playlists.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing resource.",
        "summary": "youtube.playlists.update",
        "tags": [
          "playlists"
        ],
        "operationId": "youtube.playlists.update",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/search": {
      "get": {
        "description": "Retrieves a list of search resources",
        "summary": "youtube.search.list",
        "tags": [
          "search"
        ],
        "operationId": "youtube.search.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/subscriptions": {
      "delete": {
        "description": "Deletes a resource.",
        "summary": "youtube.subscriptions.delete",
        "tags": [
          "subscriptions"
        ],
        "operationId": "youtube.subscriptions.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.subscriptions.list",
        "tags": [
          "subscriptions"
        ],
        "operationId": "youtube.subscriptions.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.subscriptions.insert",
        "tags": [
          "subscriptions"
        ],
        "operationId": "youtube.subscriptions.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/superChatEvents": {
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.superChatEvents.list",
        "tags": [
          "superChatEvents"
        ],
        "operationId": "youtube.superChatEvents.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          }
        ]
      }
    },
    "/youtube/v3/tests": {
      "post": {
        "description": "POST method.",
        "summary": "youtube.tests.insert",
        "tags": [
          "tests"
        ],
        "operationId": "youtube.tests.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          }
        ]
      }
    },
    "/youtube/v3/thirdPartyLinks": {
      "delete": {
        "description": "Deletes a resource.",
        "summary": "youtube.thirdPartyLinks.delete",
        "tags": [
          "thirdPartyLinks"
        ],
        "operationId": "youtube.thirdPartyLinks.delete",
        "deprecated": false
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.thirdPartyLinks.list",
        "tags": [
          "thirdPartyLinks"
        ],
        "operationId": "youtube.thirdPartyLinks.list",
        "deprecated": false
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.thirdPartyLinks.insert",
        "tags": [
          "thirdPartyLinks"
        ],
        "operationId": "youtube.thirdPartyLinks.insert",
        "deprecated": false
      },
      "put": {
        "description": "Updates an existing resource.",
        "summary": "youtube.thirdPartyLinks.update",
        "tags": [
          "thirdPartyLinks"
        ],
        "operationId": "youtube.thirdPartyLinks.update",
        "deprecated": false
      }
    },
    "/youtube/v3/thumbnails/set": {
      "post": {
        "description": "As this is not an insert in a strict sense (it supports uploading/setting of a thumbnail for multiple videos, which doesn't result in creation of a single resource), I use a custom verb here.",
        "summary": "youtube.thumbnails.set",
        "tags": [
          "thumbnails"
        ],
        "operationId": "youtube.thumbnails.set",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.upload"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.upload"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/videoAbuseReportReasons": {
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.videoAbuseReportReasons.list",
        "tags": [
          "videoAbuseReportReasons"
        ],
        "operationId": "youtube.videoAbuseReportReasons.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          }
        ]
      }
    },
    "/youtube/v3/videoCategories": {
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.videoCategories.list",
        "tags": [
          "videoCategories"
        ],
        "operationId": "youtube.videoCategories.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/videos": {
      "delete": {
        "description": "Deletes a resource.",
        "summary": "youtube.videos.delete",
        "tags": [
          "videos"
        ],
        "operationId": "youtube.videos.delete",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of resources, possibly filtered.",
        "summary": "youtube.videos.list",
        "tags": [
          "videos"
        ],
        "operationId": "youtube.videos.list",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "post": {
        "description": "Inserts a new resource into this collection.",
        "summary": "youtube.videos.insert",
        "tags": [
          "videos"
        ],
        "operationId": "youtube.videos.insert",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.upload"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.upload"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      },
      "put": {
        "description": "Updates an existing resource.",
        "summary": "youtube.videos.update",
        "tags": [
          "videos"
        ],
        "operationId": "youtube.videos.update",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/videos/getRating": {
      "get": {
        "description": "Retrieves the ratings that the authorized user gave to a list of specified videos.",
        "summary": "youtube.videos.getRating",
        "tags": [
          "videos"
        ],
        "operationId": "youtube.videos.getRating",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/videos/rate": {
      "post": {
        "description": "Adds a like or dislike rating to a video or removes a rating from a video.",
        "summary": "youtube.videos.rate",
        "tags": [
          "videos"
        ],
        "operationId": "youtube.videos.rate",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/videos/reportAbuse": {
      "post": {
        "description": "Report abuse for a video.",
        "summary": "youtube.videos.reportAbuse",
        "tags": [
          "videos"
        ],
        "operationId": "youtube.videos.reportAbuse",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/watermarks/set": {
      "post": {
        "description": "Allows upload of watermark image and setting it for a channel.",
        "summary": "youtube.watermarks.set",
        "tags": [
          "watermarks"
        ],
        "operationId": "youtube.watermarks.set",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.upload"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.upload"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    },
    "/youtube/v3/watermarks/unset": {
      "post": {
        "description": "Allows removal of channel watermark.",
        "summary": "youtube.watermarks.unset",
        "tags": [
          "watermarks"
        ],
        "operationId": "youtube.watermarks.unset",
        "deprecated": false,
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/youtubepartner"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/youtubepartner"
            ]
          }
        ]
      }
    }
  },
  "security": [],
  "tags": [
    {
      "name": "abuseReports"
    },
    {
      "name": "activities"
    },
    {
      "name": "captions"
    },
    {
      "name": "channelBanners"
    },
    {
      "name": "channels"
    },
    {
      "name": "channelSections"
    },
    {
      "name": "comments"
    },
    {
      "name": "commentThreads"
    },
    {
      "name": "i18nLanguages"
    },
    {
      "name": "i18nRegions"
    },
    {
      "name": "liveBroadcasts"
    },
    {
      "name": "liveChatBans"
    },
    {
      "name": "liveChatMessages"
    },
    {
      "name": "liveChatModerators"
    },
    {
      "name": "liveStreams"
    },
    {
      "name": "members"
    },
    {
      "name": "membershipsLevels"
    },
    {
      "name": "playlistItems"
    },
    {
      "name": "playlists"
    },
    {
      "name": "search"
    },
    {
      "name": "subscriptions"
    },
    {
      "name": "superChatEvents"
    },
    {
      "name": "tests"
    },
    {
      "name": "thirdPartyLinks"
    },
    {
      "name": "thumbnails"
    },
    {
      "name": "videoAbuseReportReasons"
    },
    {
      "name": "videoCategories"
    },
    {
      "name": "videos"
    },
    {
      "name": "watermarks"
    },
    {
      "name": "youtube"
    }
  ]
}